---
title: "FOXP3subnetwork"
output: html_document
---

```{r}
level_0 = 2
level_1 = 1
level_2 = 0
level_3 = -1
level_4 = -2
manual_layout = tibble::tribble(
        ~name, ~x, ~y,
        "IRF4", -0.5, level_1,
        "MYB", 0.5, level_1,
        "KMT2A", 0, level_0,
        "GATA3", 0, level_2,
        "IL2RA", -0.5, level_3,
        "FOXP3", 0.5, level_3
)
included_genes <- manual_layout$name

```

```{r}
causal_network <- read_excel("/Users/jihungu/Desktop/Thesis/RNAseq-perturbation-CD4-pipeline-master/causal_network.xlsx")

causal_network_20 <- causal_network %>%
  dplyr::filter(abs(estimate) >= 0.024) 
causal_network_25 <- causal_network %>%
  dplyr::filter(abs(estimate) >= 0.025)
causal_network_30 <- causal_network %>%
  dplyr::filter(abs(estimate) >= 0.03)

mashr <-read_excel("/Users/jihungu/Desktop/Reference/LLCB/Supplementary/mashr.xlsx")
mashr <- mashr %>%
  dplyr::filter(LFSR < 0.005)

mashr <- mashr %>%
  dplyr::rename(from = row, to = col, signed_weight = estimate)

```


```{r}
edges_df <- causal_network_20 %>%
  dplyr::rename(from = row, to = col, signed_weight = estimate)

edges_df <- edges_df %>%
  mutate(pair_id = pmap_chr(list(from, to), ~ paste(sort(c(..1, ..2)), collapse = "_"))) %>%
  group_by(pair_id) %>%
  slice_max(abs(signed_weight), n = 1) %>%
  ungroup() %>%
  select(-pair_id)
```


```{r}
edges_df = edges_df %>%
  dplyr::bind_rows(mashr)

edges_subset <- edges_df %>%
  filter(from %in% included_genes & to %in% included_genes)

nodes_subset <- tibble(name = unique(c(edges_subset$from, edges_subset$to)))

graph <- tidygraph::tbl_graph(nodes = nodes_subset, edges = edges_subset) %>%
  tidygraph::activate(nodes) %>%
  left_join(manual_layout, by = "name")

plot <- ggraph(graph, x = x, y = y) + 
  geom_edge_arc2(
    aes(colour = signed_weight),
    arrow = arrow(length = unit(0.13, "inches"), type = "closed"),
    alpha = .4,
    strength = 0.1,
    start_cap = circle(2.6, 'mm'),
    end_cap = circle(2.6, 'mm')
  ) +
  scale_edge_colour_gradient2(low = "blue", mid = "gray", high = "red") +
  geom_node_point() +
  geom_node_text(aes(label = name), size = 3, check_overlap = TRUE, repel = TRUE) +
  theme_graph(base_family = "Helvetica") +
  theme(legend.position = "top", legend.key.width = unit(1, "cm"))


print(plot)
```

# humanbase+reactome
```{r}
known <- read_excel("/Users/jihungu/Desktop/Thesis/Ground Truth/hbase_reactome.xlsx")
```


```{r}
known_pairs <- known %>%
  dplyr::mutate(pair = purrr::map2_chr(Gene1, Gene2, ~ paste(sort(c(.x, .y)), collapse = "_")))
edges_pairs <- edges_df %>%
  dplyr::mutate(pair = purrr::map2_chr(from, to, ~ paste(sort(c(.x, .y)), collapse = "_")))
```

```{r}
edges_pairs <- edges_pairs %>%
  dplyr::mutate(edge_color = ifelse(pair %in% known_pairs$pair, "green", "grey"))
edges_subset <- edges_pairs %>%  
  filter(from %in% included_genes & to %in% included_genes)

nodes_subset <- tibble(name = unique(c(edges_subset$from, edges_subset$to)))

graph <- tidygraph::tbl_graph(nodes = nodes_subset, edges = edges_subset) %>%
  tidygraph::activate(nodes) %>%
  left_join(manual_layout, by = "name")

```

```{r}
plot <- ggraph(graph, x = x, y = y) + 
  geom_edge_arc2(
    aes(colour = edge_color),
    arrow = arrow(length = unit(0.13, "inches"), type = "closed"),
    alpha = .6,
    strength = 0.1,
    start_cap = circle(2.6, 'mm'),
    end_cap = circle(2.6, 'mm')
  ) +
  scale_edge_colour_manual(values = c("grey" = "grey", "green" = "green"),
    labels = c("green" = "Already reported", "grey" = "Not reported"),
    name = "Interaction"
  ) +
  geom_node_point() +
  geom_node_text(aes(label = name), size = 3, check_overlap = TRUE, repel = TRUE) +
  theme_graph(base_family = "Helvetica") +
  theme(legend.position = "top", legend.key.width = unit(1, "cm"))

print(plot)

```

# AC,HAM/TSP, ATL
```{r}


edges_subset <- edge_eval

nodes_subset <- tibble(name = unique(c(edges_subset$from, edges_subset$to)))

graph <- tidygraph::tbl_graph(nodes = nodes_subset, edges = edges_subset) %>%
  tidygraph::activate(nodes) %>%
  left_join(manual_layout, by = "name")

plot <- ggraph(graph, x = x, y = y) + 
  geom_edge_arc2(
    aes(colour = factor(match)),
    arrow = arrow(length = unit(0.13, "inches"), type = "closed"),
    alpha = .4,
    strength = 0.1,
    start_cap = circle(2.6, 'mm'),
    end_cap = circle(2.6, 'mm')
  ) +
  scale_edge_colour_manual(
    values = c("0" = "orange", "1" = "green", "NA" = "black"),
    name = "Match"
  ) +
  geom_node_point() +
  geom_node_text(aes(label = name), size = 3, check_overlap = TRUE, repel = TRUE) +
  theme_graph(base_family = "Helvetica") +
  theme(legend.position = "top", legend.key.width = unit(1, "cm"))


print(plot)
```