---
title: "JAK-STAT subnetwork"
output: html_document
---

```{r setup, include=FALSE}
library(tidygraph)
library(ggraph)
library(ggplot2)
library(readr)
library(dplyr)
library(tibble)
library(grid)  # for unit()
edges_df <- readr::read_csv("/Users/jihungu/Desktop/Thesis/LASSO/lasso_causal_edges_all.csv") %>%
  dplyr::rename(from = Source, to = Target, signed_weight = Weight)

```

```{r}
level_0 = 16
level_1 = 8
level_2 = 0
level_3 = -4
level_4 = -2
manual_layout = tibble::tribble(
        ~name, ~x, ~y,
        "IRF4", -5, level_1,
        "JAK3", 5, level_1,
        "KMT2A", 0, level_0,
        "STAT5A", 2, level_1,
        "STAT5B", -2, level_1,
        "IL2RA", 10, level_1,
        "JAK1", 5, level_2,
        "SOS1", 16, level_2,
        "CBLB", -20, level_2,
        "IL7R", -18, level_3,
        "MYC", -16, level_2,
        "JAK2", -14, level_2,
        "IL10RA", 15, level_3,
        "PTPN6", -12, level_2,
        "IL26", -10, level_3,
        "PIAS1", -9, level_2,
        "OSM", 2, level_2,
        "IL12RB2", 17, level_3,
        "IFNG", -2, level_3,
        "IL6R", 0, level_3,
        "IL21", -1, level_3,
        "PIK3CB", 15, level_2,
        "IFNGR2", 1, level_3,
        "CCND3", -7, level_2,
        "SOCS3", -4, level_2,
        "CCND2", 4, level_2,
        "CISH", -5, level_2,
        "IL2RB", 3, level_3,
        "IL22", 9, level_3,
        "IL23R", 7, level_3,
        "IL6ST", 18, level_3,
        "LIF", 20, level_2,
        "SOCS2", 7, level_2,
        "STAT4", 4.5, level_2,
        "IL4R", 22, level_3,
        "SOCS1", 2.5, level_2,
        "IL2RG", 23, level_3,
        "IL15", 3.5, level_3,
        "IL13", 21, level_3,
        "IFNGR1", 8, level_3,
        "SPRED2", 9, level_2,
        "IL15RA", 24, level_3,
        "IFNAR2", 25, level_3,
        "IL9", 19, level_3,
        "IL21R", -11, level_3,
        "AKT3", 26, level_2,
        "IL12RB1", 14, level_3,
        "IL5", 6, level_3
)
included_genes <- manual_layout$name

```

```{r}
edges_subset <- edges_df %>%
  filter(from %in% included_genes & to %in% included_genes)

nodes_subset <- tibble(name = unique(c(edges_subset$from, edges_subset$to)))

graph <- tidygraph::tbl_graph(nodes = nodes_subset, edges = edges_subset) %>%
  tidygraph::activate(nodes) %>%
  left_join(manual_layout, by = "name")


plot <- ggraph(graph, x = x, y = y) + 
  geom_edge_arc2(
    aes(colour = signed_weight),
    arrow = arrow(length = unit(0.13, "inches"), type = "closed"),
    alpha = .4,
    strength = 0.1,
    start_cap = circle(2.6, 'mm'),
    end_cap = circle(2.6, 'mm')
  ) +
  scale_edge_colour_gradient2(low = "blue", mid = "gray", high = "red") +
  geom_node_point() +
  geom_node_text(aes(label = name), size = 3, check_overlap = TRUE, repel = TRUE) +
  theme_graph(base_family = "Helvetica") +
  theme(legend.position = "top", legend.key.width = unit(1, "cm"))

ggsave("lasso_manual_network.pdf", plot, width = 12, height = 8, units = "in")

print(plot)
```

```{r}
edges_df <- readr::read_csv("/Users/jihungu/Desktop/Thesis/DCDI/dcdi_dsf_edges_84x13000.csv") %>%
  dplyr::rename(from = Source, to = Target, signed_weight = Weight)
edges_subset <- edges_df %>%
  filter(from %in% included_genes & to %in% included_genes)

nodes_subset <- tibble(name = unique(c(edges_subset$from, edges_subset$to)))

graph <- tidygraph::tbl_graph(nodes = nodes_subset, edges = edges_subset) %>%
  tidygraph::activate(nodes) %>%
  left_join(manual_layout, by = "name")


plot <- ggraph(graph, x = x, y = y) + 
  geom_edge_arc2(
    aes(colour = signed_weight),
    arrow = arrow(length = unit(0.13, "inches"), type = "closed"),
    alpha = .4,
    strength = 0.1,
    start_cap = circle(2.6, 'mm'),
    end_cap = circle(2.6, 'mm')
  ) +
  scale_edge_colour_gradient2(low = "blue", mid = "gray", high = "red") +
  geom_node_point() +
  geom_node_text(aes(label = name), size = 3, check_overlap = TRUE, repel = TRUE) +
  theme_graph(base_family = "Helvetica") +
  theme(legend.position = "top", legend.key.width = unit(1, "cm"))

ggsave("DCDIDSF_manual_network.pdf", plot, width = 12, height = 8, units = "in")

print(plot)
```

```{r}
edges_df <- readr::read_csv("/Users/jihungu/Desktop/Thesis/DCDFG/dcdfg_edges_84x13000.csv") %>%
  dplyr::rename(from = Source, to = Target, signed_weight = Weight)
edges_subset <- edges_df %>%
  filter(from %in% included_genes & to %in% included_genes) %>%
  filter(abs(signed_weight) >= 0.0125)


nodes_subset <- tibble(name = unique(c(edges_subset$from, edges_subset$to)))

graph <- tidygraph::tbl_graph(nodes = nodes_subset, edges = edges_subset) %>%
  tidygraph::activate(nodes) %>%
  left_join(manual_layout, by = "name")


plot <- ggraph(graph, x = x, y = y) + 
  geom_edge_arc2(
    aes(colour = signed_weight),
    arrow = arrow(length = unit(0.13, "inches"), type = "closed"),
    alpha = .4,
    strength = 0.1,
    start_cap = circle(2.6, 'mm'),
    end_cap = circle(2.6, 'mm')
  ) +
  scale_edge_colour_gradient2(low = "blue", mid = "gray", high = "red") +
  geom_node_point() +
  geom_node_text(aes(label = name), size = 3, check_overlap = TRUE, repel = TRUE) +
  theme_graph(base_family = "Helvetica") +
  theme(legend.position = "top", legend.key.width = unit(1, "cm"))

ggsave("DCDFG_manual_network.pdf", plot, width = 12, height = 8, units = "in")

print(plot)
```

```{r}
library(ReactomePA)
library(org.Hs.eg.db)

# SYMBOL → ENTREZID
entrez_ids <- AnnotationDbi::mapIds(
  org.Hs.eg.db,
  keys = included_genes,
  column = "ENTREZID",
  keytype = "SYMBOL",
  multiVals = "first"
)


# Reactome pathway enrichment
reactome_res <- enrichPathway(gene = entrez_ids, readable = TRUE)

# View top pathways
head(as.data.frame(reactome_res))
```



```{r}
level_0 = 16
level_1 = 8
level_2 = 0
level_3 = -4
level_4 = -2
manual_layout = tibble::tribble(
        ~name, ~x, ~y,
        "IRF4", -5, level_1,
        "JAK3", 5, level_1,
        "KMT2A", 0, level_0,
        "STAT5A", 2, level_1,
        "STAT5B", -2, level_1,
        "IL2RA", 10, level_1,
        "JAK1", 5, level_2,
        "SOS1", 16, level_2,
        "CBLB", -20, level_2,
        "IL7R", -18, level_3,
        "MYC", -16, level_2,
        "JAK2", -14, level_2,
        "IL10RA", 15, level_3,
        "PTPN6", -12, level_2,
        "IL26", -10, level_3,
        "PIAS1", -9, level_2,
        "OSM", 2, level_2,
        "IL12RB2", 17, level_3,
        "IFNG", -2, level_3,
        "IL6R", 0, level_3,
        "IL21", -1, level_3,
        "PIK3CB", 15, level_2,
        "IFNGR2", 1, level_3,
        "CCND3", -7, level_2,
        "SOCS3", -4, level_2,
        "CCND2", 4, level_2,
        "CISH", -5, level_2,
        "IL2RB", 3, level_3,
        "IL22", 9, level_3,
        "IL23R", 7, level_3,
        "IL6ST", 18, level_3,
        "LIF", 20, level_2,
        "SOCS2", 7, level_2,
        "STAT4", 4.5, level_2,
        "IL4R", 22, level_3,
        "SOCS1", 2.5, level_2,
        "IL2RG", 23, level_3,
        "IL15", 3.5, level_3,
        "IL13", 21, level_3,
        "IFNGR1", 8, level_3,
        "SPRED2", 9, level_2,
        "IL15RA", 24, level_3,
        "IFNAR2", 25, level_3,
        "IL9", 19, level_3,
        "IL21R", -11, level_3,
        "AKT3", 26, level_2,
        "IL12RB1", 14, level_3,
        "IL5", 6, level_3
)
included_genes <- manual_layout$name

```

```{r}
causal_network <- read_excel("/Users/jihungu/Desktop/Thesis/RNAseq-perturbation-CD4-pipeline-master/causal_network.xlsx")

causal_network_20 <- causal_network %>%
  dplyr::filter(abs(estimate) >= 0.020) 
causal_network_25 <- causal_network %>%
  dplyr::filter(abs(estimate) >= 0.025)
causal_network_30 <- causal_network %>%
  dplyr::filter(abs(estimate) >= 0.03)

mashr <-read_excel("/Users/jihungu/Desktop/Reference/LLCB/Supplementary/mashr.xlsx")
mashr <- mashr %>%
  dplyr::filter(LFSR < 0.005)

mashr <- mashr %>%
  dplyr::rename(from = row, to = col, signed_weight = estimate)

```


```{r}
edges_df <- causal_network_25 %>%
  dplyr::rename(from = row, to = col, signed_weight = estimate)
```


```{r}
edges_df = edges_df %>%
  dplyr::bind_rows(mashr)

edges_subset <- edges_df %>%
  filter(from %in% included_genes & to %in% included_genes)

nodes_subset <- tibble(name = unique(c(edges_subset$from, edges_subset$to)))

graph <- tidygraph::tbl_graph(nodes = nodes_subset, edges = edges_subset) %>%
  tidygraph::activate(nodes) %>%
  left_join(manual_layout, by = "name")

plot <- ggraph(graph, x = x, y = y) + 
  geom_edge_arc2(
    aes(colour = signed_weight),
    arrow = arrow(length = unit(0.13, "inches"), type = "closed"),
    alpha = .4,
    strength = 0.1,
    start_cap = circle(2.6, 'mm'),
    end_cap = circle(2.6, 'mm')
  ) +
  scale_edge_colour_gradient2(low = "blue", mid = "gray", high = "red") +
  geom_node_point() +
  geom_node_text(aes(label = name), size = 3, check_overlap = TRUE, repel = TRUE) +
  theme_graph(base_family = "Helvetica") +
  theme(legend.position = "top", legend.key.width = unit(1, "cm"))


print(plot)
```

# humanbase+reactome
```{r}
known <- read_excel("/Users/jihungu/Desktop/Thesis/Ground Truth/hbase_reactome.xlsx")
```


```{r}
known_pairs <- known %>%
  dplyr::mutate(pair = purrr::map2_chr(Gene1, Gene2, ~ paste(sort(c(.x, .y)), collapse = "_")))
edges_pairs <- edges_df %>%
  dplyr::mutate(pair = purrr::map2_chr(from, to, ~ paste(sort(c(.x, .y)), collapse = "_")))
```

```{r}
edges_pairs <- edges_pairs %>%
  dplyr::mutate(edge_color = ifelse(pair %in% known_pairs$pair, "green", "grey"))
edges_subset <- edges_pairs %>%  
  filter(from %in% included_genes & to %in% included_genes)

nodes_subset <- tibble(name = unique(c(edges_subset$from, edges_subset$to)))

graph <- tidygraph::tbl_graph(nodes = nodes_subset, edges = edges_subset) %>%
  tidygraph::activate(nodes) %>%
  left_join(manual_layout, by = "name")

```

```{r}
plot <- ggraph(graph, x = x, y = y) + 
  geom_edge_arc2(
    aes(colour = edge_color),
    arrow = arrow(length = unit(0.13, "inches"), type = "closed"),
    alpha = .6,
    strength = 0.1,
    start_cap = circle(2.6, 'mm'),
    end_cap = circle(2.6, 'mm')
  ) +
  scale_edge_colour_manual(values = c("grey" = "grey", "green" = "green"),
    labels = c("green" = "Already reported", "grey" = "Not reported"),
    name = "Interaction"
  ) +
  geom_node_point() +
  geom_node_text(aes(label = name), size = 3, check_overlap = TRUE, repel = TRUE) +
  theme_graph(base_family = "Helvetica") +
  theme(legend.position = "top", legend.key.width = unit(1, "cm"))

print(plot)

```


# AC,HAM/TSP, ATL
```{r}


edges_subset <- edge_eval

nodes_subset <- tibble(name = unique(c(edges_subset$from, edges_subset$to)))

graph <- tidygraph::tbl_graph(nodes = nodes_subset, edges = edges_subset) %>%
  tidygraph::activate(nodes) %>%
  left_join(manual_layout, by = "name")

plot <- ggraph(graph, x = x, y = y) + 
  geom_edge_arc2(
    aes(colour = factor(match)),
    arrow = arrow(length = unit(0.13, "inches"), type = "closed"),
    alpha = .4,
    strength = 0.1,
    start_cap = circle(2.6, 'mm'),
    end_cap = circle(2.6, 'mm')
  ) +
  scale_edge_colour_manual(
    values = c("0" = "orange", "1" = "green", "NA" = "black"),
    name = "Match"
  ) +
  geom_node_point() +
  geom_node_text(aes(label = name), size = 3, check_overlap = TRUE, repel = TRUE) +
  theme_graph(base_family = "Helvetica") +
  theme(legend.position = "top", legend.key.width = unit(1, "cm"))


print(plot)
```

