---
title: "Evaluating O/E"
output: html_document
---
#jakstat
```{r}
edges <- read_excel("/Users/jihungu/Desktop/Thesis/MyRCode/HTLV-1/Jak_stat_edges.xlsx")
```

#foxp3 il2ra
```{r}
edges <- read_excel("/Users/jihungu/Desktop/Thesis/MyRCode/HTLV-1/FOXP3_edges.xlsx")
```

# AC
```{r}
AC <- read_excel("/Users/jihungu/Desktop/Thesis/MyRCode/HTLV-1/AC.xlsx")
AC <- AC %>%
  mutate(SYMBOL = ifelse(SYMBOL == "MLL", "KMT2A", SYMBOL))
```

```{r}
library(dplyr)

get_sign <- function(x) {
  ifelse(x > 0, 1, ifelse(x < 0, -1, 0))
}



edge_eval <- edges %>%
  left_join(AC, by = c("from" = "SYMBOL")) %>%
  rename(logFC_from = logFC) %>%
  left_join(AC, by = c("to" = "SYMBOL")) %>%
  rename(logFC_to = logFC)

edge_eval <- edge_eval %>%
  mutate(
    sign_weight = get_sign(signed_weight),
    sign_from = get_sign(logFC_from),
    sign_to = get_sign(logFC_to),
    match = ifelse(sign_weight == sign_from * sign_to, 1, 0)
  )

match_rate <- mean(edge_eval$match, na.rm = TRUE)
cat("Match Rate):", round(match_rate * 100, 2), "%\n")

head(edge_eval %>% select(from, to, signed_weight, logFC_from, logFC_to, match), 10)

```


# HAM
```{r}
HAM <- read_excel("/Users/jihungu/Desktop/Thesis/MyRCode/HTLV-1/HAM.xlsx")
HAM <- HAM %>%
  mutate(SYMBOL = ifelse(SYMBOL == "MLL", "KMT2A", SYMBOL))
```

```{r}
library(dplyr)

# 1. sign 함수 정의
get_sign <- function(x) {
  ifelse(x > 0, 1, ifelse(x < 0, -1, 0))
}


edge_eval <- edges %>%
  left_join(HAM, by = c("from" = "SYMBOL")) %>%
  rename(logFC_from = logFC) %>%
  left_join(HAM, by = c("to" = "SYMBOL")) %>%
  rename(logFC_to = logFC)

edge_eval <- edge_eval %>%
  mutate(
    sign_weight = get_sign(signed_weight),
    sign_from = get_sign(logFC_from),
    sign_to = get_sign(logFC_to),
    match = ifelse(sign_weight == sign_from * sign_to, 1, 0)
  )

match_rate <- mean(edge_eval$match, na.rm = TRUE)
cat("Match Rate):", round(match_rate * 100, 2), "%\n")

head(edge_eval %>% select(from, to, signed_weight, logFC_from, logFC_to, match), 10)

```

# ATl
```{r}
ATL <- read_excel("/Users/jihungu/Desktop/Thesis/MyRCode/HTLV-1/ATL.xlsx")
ATL <- ATL %>%
  mutate(GENE_SYMBOL = ifelse(GENE_SYMBOL == "MLL", "KMT2A", GENE_SYMBOL))
```

```{r}
library(dplyr)

get_sign <- function(x) {
  ifelse(x > 0, 1, ifelse(x < 0, -1, 0))
}


edge_eval <- edges %>%
  left_join(ATL, by = c("from" = "GENE_SYMBOL")) %>%
  rename(logFC_from = logFC) %>%
  left_join(ATL, by = c("to" = "GENE_SYMBOL")) %>%
  rename(logFC_to = logFC)

edge_eval <- edge_eval %>%
  mutate(
    sign_weight = get_sign(signed_weight),
    sign_from = get_sign(logFC_from),
    sign_to = get_sign(logFC_to),
    match = ifelse(sign_weight == sign_from * sign_to, 1, 0)
  )

match_rate <- mean(edge_eval$match, na.rm = TRUE)
cat("(Match Rate):", round(match_rate * 100, 2), "%\n")

head(edge_eval %>% select(from, to, signed_weight, logFC_from, logFC_to, match), 10)
#edge_eval <- edge_eval %>%
#  select(from, to, signed_weight, logFC_from, logFC_to, match)
```